### ISSUE TITLE
Checklist for adding a new resource

### ISSUE THREAD

**Issue by RaitoBezarius** [NixOS/nixops-aws#10]
I am in the process of adding a DBSubnetGroup resource to this plugin, I have somehow copied the code from EC2 Security Group resource and tried to adapt everything to make it work, so far I understood I need to:

- [x] Create a Nix config file, like `ec2-rds-dbsubnet-group.nix` with `mkOption`.
- [x] Add it to the `default.nix` using `evalResources` (which I am not sure to understand what it does exactly).
- [x] Create a Python logic file, like `ec2_rds_dbsubnet_group.py` which implements a Definition and a State and to ensure in the definition that resource type are matching.
- [x] Import it into the `nixops.resources.__init__.py` file.

Did I miss something? While my code is "working", it's not picking up the new resource declaration in one of my `infrastructure.nix` file.
